### ISSUE TITLE
Version 1.0.0 Roadmap

### ISSUE THREAD

**Issue by maxdevos49** [maxdevos49/protopaintv2#3]
# Version 1.0.0 Roadmap

First version of Protopaint will have drawing and CLUI support.

Requirements:
- [ ] #4
- [ ] Webcomponent Template/Abstract class
- [ ] Dependency Injection Support
- [ ] SVG drawing library
  - [ ] CLUI API wrapper
  - [ ] Add
  - [ ] Remove
  - [ ] Rotate
  - [ ] Select
  - [ ] Translate
  - [ ] SetColor
  - [ ] Fill
- [ ] Window frame API
  - [ ] CLUI API wrapper
  - [ ] Resize
  - [ ] Hide/Show
  - [ ] Collapse
- [ ] Canvas API
  - [ ] CLUI API wrapper
  - [ ] Resize
  - [ ] Scale
  - [ ] Translate
- [ ] View API
  - [ ] CLUI API wrapper
  - [ ] Full Screen
  - [ ] Zen Mode
 - [ ] File API
   - [ ] CLUI API wrapper
   - [ ] Save + Load
   - [ ] Export to SVG, PNG
- [ ] Undo/Redo Reducer
  - [ ] CLUI API wrapper 
- [ ] Notification API
- [ ] File Menu API
- [ ] Footer Menu API
